version: '3.3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - './database/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d'
      - 'postgres:/var/lib/postgresql/data'
      
      

volumes:
  postgres:
